=== Saed-Hamdy/DBMS/Data Bases/mydb2/clients.dtd
<!ELEMENT clients (row*)>
<!ELEMENT row (password,user,Age)>
<!ELEMENT password (#PCDATA)>
<!ELEMENT user (#PCDATA)>
<!ELEMENT Age (#PCDATA)>

<!ATTLIST students coulmn0 CDATA #REQUIRED >
<!ATTLIST students coulmn1 CDATA #REQUIRED >
<!ATTLIST students coulmn2 CDATA #REQUIRED >
<!ATTLIST students sizeCol CDATA #REQUIRED >
<!ATTLIST students sizeRow CDATA #REQUIRED >

<!ATTLIST row id CDATA #REQUIRED >

=== Saed-Hamdy/DBMS/Data Bases/mydb2/clients.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE clients SYSTEM "clients.dtd">
<clients coulmn0="password:int" coulmn1="user:varchar" coulmn2="Age:int" sizeCol="3" sizeRow="4">
<row id="0">
<password>1234</password>
<user>mohamed ahmed</user>
<Age>1</Age>
</row>
<row id="1">
<password>1234</password>
<user>ahmed</user>
<Age>2</Age>
</row>
<row id="2">
<password>1234</password>
<user>ali</user>
<Age>3</Age>
</row>
<row id="3">
<password>1234</password>
<user>ali</user>
<Age> </Age>
</row>
</clients>
