=== Saed-Hamdy/DBMS/DBMS/Data Bases/mydb/clients.dtd
<!ELEMENT clients (row+)>
<!ELEMENT row (ID,Name,Age)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Age (#PCDATA)>

<!ATTLIST students coulmn0 NMTOKEN #REQUIRED >
<!ATTLIST students coulmn1 NMTOKEN #REQUIRED >
<!ATTLIST students coulmn2 NMTOKEN #REQUIRED >
<!ATTLIST students sizeCol NMTOKEN #REQUIRED >
<!ATTLIST students sizeRow NMTOKEN #REQUIRED >

<!ATTLIST row id NMTOKEN #REQUIRED >

=== Saed-Hamdy/DBMS/DBMS/Data Bases/mydb/clients.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE clients SYSTEM "clients.dtd">
<clients coulmn0="ID:int" coulmn1="Name:varchar" coulmn2="Age:int" sizeCol="3" sizeRow="2">
<row id="0">
<ID>1</ID>
<Name>ahmed</Name>
<Age>12</Age>
</row>
<row id="1">
<ID>1</ID>
<Name>ahmed mohamed</Name>
<Age>1234</Age>
</row>
</clients>
